version: "3.7"

secrets:
  database_password:
    file: ./secrets/.database_password
  proxy_password:
    file: ./secrets/.proxy_password

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
services:

  webui:
    secrets:
      - proxy_password  
    build:
      context: ./webui
      dockerfile: Dockerfile.dev
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
        NODE_ENV: development    
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-webui-dev  
    ports:
      - "8080:3000"
    volumes:
      - ./webui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  cms:
    secrets:
      - database_password
      - proxy_password  
    build:
      context: ./cms
      dockerfile: Dockerfile.dev
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}     
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
        DATABASE_CLIENT: ${DATABASE_CLIENT}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_SSL: ${DATABASE_SSL}
        AUTHENTICATION_DATABASE: ${AUTHENTICATION_DATABASE}
        NODE_ENV: development
        BASE_VERSION: 14-alpine
        STRAPI_VERSION: 3.6.8
        STRAPI_LOG_LEVEL: debug
        USER: ${USER}
    user: ${USER}    
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-cms-dev      
    ports:
      - "1436:1337"
    volumes:
      - ./cms:/srv/app
